all: taskmanager.o processes.o
	gcc -o taskmanager taskmanager.o processes.o
processes.o: processes.c processes.h
	gcc -c processes.c
taskmanager.o: taskmanager.c processes.h
	gcc -c taskmanager.c
clean:
	rm -f *.o taskmanager
cleanwindows:
	del /Q *.o taskmanager.exe